version: "3.9"

services:
  repertoire_app:
    build:
      context: ./backend
    container_name: repertoire_app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    environment: []